version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:12.22.12
    machine:
    steps:
      - checkout
      - run: 
             name: Build docker images
             command: |
                      node --version

