version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:12.22.12
    machine:
    steps:
      - checkout
      - run: 
             name: Build docker images
             command: |
                      node --version
                      echo "------- Building images ---------"
                      docker build -t udagram-api-feed ./udagram-api-feed
                      docker build -t udagram-api-user ./udagram-api-user
                      docker build -t udagram-frontend ./udagram-frontend
                      docker build -t udagram-api-feed ./reverseproxy

                      echo "------- Start tagging images ---------"
                      docker tag udagram-api-feed peggylicious/udagram-api-feed:v1
                      docker tag udagram-api-feed peggylicious/udagram-api-user:v1
                      docker tag udagram-api-feed peggylicious/udagram-frontend:v1
                      docker tag udagram-api-feed peggylicious/udagram-reverseproxy:v1

                      echo "------- Log in to docker hub ---------"

                      echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin

                      docker push peggylicious/udagram-api-feed:v1
                      docker push peggylicious/udagram-api-user:v1
                      docker push peggylicious/udagram-frontend:v1
                      docker push peggylicious/udagram-reverseproxy:v1
# Do similar for other three images

